# Generated by Django 4.0.2 on 2022-02-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avlod21', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='image_cours',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
